### PR TITLE
fix: Update shasum for MetaMask Flask version 10.31.0-flask.0

### LINKED ISSUE #258: Failed to fetch Snap "npm:@chainsafe/filsnap": Invalid Snap manifest: manifest shasum does not match computed shasum..
I am trying to install it from https://filsnap.chainsafe.io in Brave Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit) on (Fedora Workstation) Linux and it asks _Permission request - Allow this site to: Connect to @chainsafe/filsnap._ where I click Connect which causes _Request failed - Failed to fetch Snap "npm:@chainsafe/filsnap": Invalid Snap manifest: manifest shasum does not match computed shasum.._

[filsnap.chainsafe.io-1685909021882.log](https://github.com/ChainSafe/filsnap/files/11646558/filsnap.chainsafe.io-1685909021882.log) is full log I have exported from the Developers Tools.

### PR DESCRIPTION
**Pull request by vorburger**
I suspect this should fix #258.

Can I get some... FIL... something... GitCoin... whatever... 🥇 appreciation 😼  for this?

### CODE REVIEW

**Comment by vorburger** [comment]
> license/cla Expected — Waiting for status to be reported

How / where do I sign your CLA?

**Comment by mpetrunic** [comment]
> > license/cla Expected — Waiting for status to be reported
> 
> How / where do I sign your CLA?

We don't have CLA on this repo, status check was some remnant from before

**Comment by vorburger** [comment]
@mpetrunic ACK, the CLA Check has now disappeared. But there is now a build failure due to:

```
Run echo "Snap manifest not updated: packages/snap/snap.manifest.json"
Snap manifest not updated: packages/snap/snap.manifest.json
Error: Process completed with exit code [1](https://github.com/ChainSafe/filsnap/actions/runs/5171557832/jobs/9321252724?pr=260#step:10:1).
```

which... doesn't really make a whole lot of sense? This PR **_IS_** updating `packages/snap/snap.manifest.json`, so there must be something wrong with that check.

**Comment by vorburger** [comment]
> Just checked locally, you didn't do something right, the shasum on master is the correct one. 

@mpetrunic nope, I have to most respectfully disagree with you, that seems to be broken, and causes https://github.com/ChainSafe/filsnap/issues/258, as also reported e.g. on https://github.com/ChainSafe/filsnap/issues/257, because of https://github.com/MetaMask/snaps/issues/1304, as confirmed by @FrederikBolding. To the best of my knowledge, this PR should fix that issue. Perhaps you could consider re-opening this PR?

> What commands did you run to get this sha?

I [have documented that here](https://github.com/ChainSafe/filsnap/issues/258#issuecomment-1575759416).

**Comment by mpetrunic** [comment]
You forgot to update snaps-cli and build error related to that update in your PR. Replaced by #261

**Pull request closed without merging**
