### PR TITLE
Use newer glif/filecoin-number package

### LINKED ISSUE #110: Replace deprecated @openworklabs/filecoin-number
Replace [@openworklabs/filecoin-number](https://www.npmjs.com/package/@openworklabs/filecoin-number) (as it is deprecated) with 
[@glif/filecoin-number](https://www.npmjs.com/package/@glif/filecoin-number). Some SES evaluation errors need to be resolved for this to work.

### PR DESCRIPTION
**Pull request by Schwartz10**
resolves #110

### CODE REVIEW

**Review by mpetrunic — APPROVED** [review]

**Comment by mpetrunic** [comment]
@MakMuftic @rekmarks Seems like our build pipeline has issues with import/export in filecoin-number library

**Comment by rekmarks** [comment]
@mpetrunic my first guess is that it's because the new dep is [transpiled to `esnext`](https://github.com/glifio/modules/blob/primary/tsconfig.json#L4), and `mm-snap` assumes that Snap source code uses CommonJS and not ESM. However, the error looks like it comes from `eslint` (`sourceType` is a key in ESLint configs), so maybe it would work if we can get around the lint issue.

Troubleshooting this is complicated by the use of `nf-snap`. Did you guys look into PRing your changes against [the new `snaps-cli` package](https://github.com/MetaMask/snaps-skunkworks/tree/main/packages/snaps-cli)?

**Comment by Schwartz10** [comment]
Whoops sorry @mpetrunic for taking this PR only part way to the finish line... 

`@glif/filecoin-number` gets [built for node and browser](https://github.com/glifio/modules/blob/primary/packages/filecoin-number/package.json#L11-L13) environments - i notice the build is failing from `@glif/filecoin-number/lib` (browser). You may have better results importing from the `/dist` directory which is built for node (and is using `require` statements instead of `import`)?

Also, the package has its own type definitions now, so you can safely delete https://github.com/ChainSafe/filsnap/blob/master/packages/snap/%40types/filecoin-number/index.d.ts if you want!

**Comment by rekmarks** [comment]
Thank you @Schwartz10 for your suggestion! I think that's the fastest path forward for the time being.

Nevertheless, after investigating further, I'm pretty sure the error is coming directly from `browserify`, and `mm-snap build` should be updated to handle ESM in the source code by transpiling it to CommonJS using Babel.

In the near future, we will probably make Snap development less reliant on `mm-snap` build and try to create bundler plugins for Snap development instead.

**Comment by mpetrunic** [comment]
> Troubleshooting this is complicated by the use of nf-snap. Did you guys look into PRing your changes against the new snaps-cli package?

I remember I upstreamed those changes before: https://github.com/MetaMask/snaps-cli/pull/50
And I see that code in new monorepo so not sure where the error is. I remember @MakMuftic debugged those?

**Comment by rekmarks** [comment]
@mpetrunic @MakMuftic I suspect https://github.com/MetaMask/snaps-skunkworks/pull/185 will resolve this issue.

**Comment by mpetrunic** [comment]
> @mpetrunic @MakMuftic I suspect [MetaMask/snaps-skunkworks#185](https://github.com/MetaMask/snaps-skunkworks/pull/185) will resolve this issue.

Will try it out, I switched in this PR to import from "/dist" of library and that seemed to fix errors.

**Comment by mpetrunic** [comment]
@rekmarks without dist I still get import/export error. With dist I get ses error again: `TypeError: Cannot assign to read only property 'Symbol(Symbol.iterator)' of object '[object Generator]'`

**Comment by mpetrunic** [comment]
@MakMuftic This is ready. I still had to use /dist and I removed some sketchy line of code but everything seems to work.

**Review by MakMuftic — APPROVED** [review]

**Pull request merged**
